#100TeVParticles.sub -- extract partices of particular energy

Folder  = $(Item)
executable = /data/user/dpankova/double_pulse/Extract_Data_from_I3Files.py
arguments = -o NewFormat_All_MCTree_NuMu_$INT(Folder) -i /data/ana/Cscd/StartingEvents/NuGen_new/NuMu/medium_energy/IC86_flasher_p1=0.3_p2=0.0/l2/$INT(Folder)/l2_*.i3.zst -gcd /data/user/dpankova/double_pulse/GeoCalibDetectorStatus_2013.56429_V1_Modified.i3.gz -t genie
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/Extract_Data_NuMu_$INT(Folder).log
output = /scratch/dpankova/double_pulse/Extract_Data_NuMu_$INT(Folder).out
error = /scratch/dpankova/double_pulse/Extract_Data_NuMu_$INT(Folder).error
should_transfer_files   = YES
request_cpus = 1
request_memory = 15GB                       
request_disk = 7GB 
queue 1 in (1,2,3,4,5,6,7,8,9,10,11,12,13)