#Extrat some info about each event from the i3 files

Folder  = $(Item)
executable = /data/user/dpankova/double_pulse/Extract_Data_from_I3Files.py
arguments = -o NewFormat_All_MCTree_Corsika_$INT(Folder,%02d)000_$INT(Folder,%02d)999 -i  /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/11057/$INT(Folder,%02d)000-$INT(Folder,%02d)999/Level2_IC86.2012_corsika.011057.*.i3.bz2 -gcd /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/11057/01000-01999/GeoCalibDetectorStatus_2012.56063_V1.i3.gz -t corsika 
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/Extract_Data_Corsika_$INT(Folder).log
output = /scratch/dpankova/double_pulse/Extract_Data_Corsika_$INT(Folder).out
error = /scratch/dpankova/double_pulse/Extract_Data_Corsika_$INT(Folder).error
should_transfer_files   = YES
request_cpus = 1
request_memory = 7GB                       
request_disk = 7GB 
queue 1 in (0,1,2,3,4,5)