#100TeVParticles.sub -- extract partices of particular energy

Folder  = 6
FolderPad = $(Folder) - 1
Num = 6
executable = /data/user/dpankova/double_pulse/Make_NewFormat.py
arguments = -it 1 -o NewFormat_NuMuCC_Qtot1000_Qst400_$INT(Folder)_$INT(Num) -i /data/ana/Cscd/StartingEvents/NuGen_new/NuMu/medium_energy/IC86_flasher_p1=0.3_p2=0.0/l2/$INT(Folder)/l2_000$INT(FolderPad,%02d)$INT(Num)*.i3.zst 
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/NewFormat_NuMu_CC_$INT(Folder)_$INT(Num).log
output = /scratch/dpankova/double_pulse/NewFormat_NuMu_CC_$INT(Folder)_$INT(Num).out
error = /scratch/dpankova/double_pulse/NewFormat_NuMu_CC_$INT(Folder)_$INT(Num).error
should_transfer_files = YES
request_cpus = 1
request_memory = 10GB                       
request_disk = 10GB 
queue 1 