#Make images

Type = NuTau
It = 1
Sim = genie
Sys = three
executable = /data/user/dpankova/double_pulse/Make_Images.py
arguments = -it $INT(It) -o Images_$(Sys)_$(Type)_$INT(It)_1_00000001 -i /data/ana/Cscd/StartingEvents/NuGen_new/$(Type)/medium_energy/IC86_flasher_p1=0.3_p2=3.0/l2/1/l2_00000001.i3.zst -gcd /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/11057/01000-01999/GeoCalibDetectorStatus_2012.56063_V1.i3.gz -t $(Sim)
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/Make_Images_$(Sys)_$(Type)_$INT(It).log
output = /scratch/dpankova/double_pulse/Make_Images_$(Sys)_$(Type)_$INT(It).out
error = /scratch/dpankova/double_pulse/Make_Images_$(Sys)_$(Type)_$INT(It).error
should_transfer_files   = YES
transfer_input_files = /data/user/dpankova/double_pulse/Reconstruction.py, /data/user/dpankova/double_pulse/QTot.py, /data/user/dpankova/double_pulse/PolygonContainment.py
request_cpus = 1
request_memory = 8GB                       
request_disk = 1GB 
queue 1 