#Make images

Fold  = $(folder)
Num = $(number)
Sim = corsika
Dataset = $(dset)

executable = /data/user/dpankova/double_pulse/Make_Images.py
arguments = -o /data/user/dpankova/double_pulse/images/Corsika_$(Dataset)/Images_Corsika_$(Dataset)_$INT(Fold,%02d)000_$INT(Fold,%02d)999_$INT(Num,%03d) -i  /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/$(Dataset)/$INT(Fold,%02d)000-$INT(Fold,%02d)999/Level2_IC86.2012_corsika.0$(Dataset).$INT(Fold,%03d)$INT(Num,%03d)*.i3.bz2  -gcd /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/11058/01000-01999/GeoCalibDetectorStatus_2012.56063_V1.i3.gz -t $(Sim) -set $(Dataset)
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/Make_Images_Corsika_$(Dataset)_$INT(Fold,%02d)_$INT(Num,%03d).log
output = /scratch/dpankova/double_pulse/Make_Images_Corsika_$(Dataset)_$INT(Fold,%02d)_$INT(Num,%03d).out
error = /scratch/dpankova/double_pulse/Make_Images_Corsika_$(Dataset)_$INT(Fold,%02d)_$INT(Num,%03d).error
should_transfer_files   = YES
transfer_input_files = /data/user/dpankova/double_pulse/Reconstruction.py, /data/user/dpankova/double_pulse/QTot.py, /data/user/dpankova/double_pulse/PolygonContainment.py
request_cpus = 1
request_memory = 6GB                       
request_disk = 0.5GB 
queue 
