#Make images

Folder  = $(Item)
Num = $(Step)
Sim = corsika
Dataset = 11058

executable = /data/user/dpankova/double_pulse/Make_Images.py
arguments = -o /data/user/dpankova/double_pulse/images/Corsika_$(Dataset)/Images_Corsika_$(Dataset)_$INT(Folder,%02d)000_$INT(Folder,%02d)999_$INT(Num,%03d) -i  /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/$(Dataset)/$INT(Folder,%02d)000-$INT(Folder,%02d)999/Level2_IC86.2012_corsika.0$(Dataset).$INT(Folder,%03d)$INT(Num,%03d)*.i3.bz2  -gcd /data/sim/IceCube/2012/filtered/level2/CORSIKA-in-ice/11058/01000-01999/GeoCalibDetectorStatus_2012.56063_V1.i3.gz -t $(Sim) -set $(Dataset)
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/Make_Images_Corsika_11058_$INT(Folder)_$INT(Num,%03d).log
output = /scratch/dpankova/double_pulse/Make_Images_Corsika_11058_$INT(Folder)_$INT(Num,%3d).out
error = /scratch/dpankova/double_pulse/Make_Images_Corsika_11058_$INT(Folder)_$INT(Num,%03d).error
should_transfer_files   = YES
transfer_input_files = /data/user/dpankova/double_pulse/Reconstruction.py, /data/user/dpankova/double_pulse/QTot.py, /data/user/dpankova/double_pulse/PolygonContainment.py
request_cpus = 1
request_memory = 1GB                       
request_disk = 0.1GB 
queue 1000 in (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31)
