#100TeVParticles.sub -- extract partices of particular energy

Folder  = $(Step)+2
executable = /data/user/dpankova/double_pulse/NewFormat.py
arguments = -p 15 -o NewFormat_NuTauCC_Qtot1000_Qst300_$INT(Folder) -i /data/ana/Cscd/StartingEvents/NuGen_new/NuTau/medium_energy/IC86_flasher_p1=0.3_p2=0.0/l2/$INT(Folder)/l2_00*.i3.zst 
run_as_owner = True
initialdir = /data/user/dpankova/double_pulse/
log = /scratch/dpankova/double_pulse/100TeVParticles_NuTau_CC_$INT(Folder).log
output = /scratch/dpankova/double_pulse/100TeVParticles_NuTau_CC_$INT(Folder).out
error = /scratch/dpankova/double_pulse/100TeVParticles_NuTau_CC_$INT(Folder).error
should_transfer_files   = YES
request_cpus = 1
request_memory = 12GB                                                                                                               
request_disk = 12GB 
queue 